// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsWqGFkxEajPRPxZIfN2zuA_UupbD9pHg',
    appId: '1:673318846822:web:81d52dcb2b8cf1d695c8a7',
    messagingSenderId: '673318846822',
    projectId: 'kadu-db',
    authDomain: 'kadu-db.firebaseapp.com',
    storageBucket: 'kadu-db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgZu0NTVelp6oBAeOd4JxS1tbAf9rPW9A',
    appId: '1:673318846822:android:7621eac850d6e53195c8a7',
    messagingSenderId: '673318846822',
    projectId: 'kadu-db',
    storageBucket: 'kadu-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeKgfqJRtZZOHKL8gbyIEzcaW6EwvAfko',
    appId: '1:673318846822:ios:d7478b555f0c0d3495c8a7',
    messagingSenderId: '673318846822',
    projectId: 'kadu-db',
    storageBucket: 'kadu-db.firebasestorage.app',
    iosBundleId: 'com.example.kadu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeKgfqJRtZZOHKL8gbyIEzcaW6EwvAfko',
    appId: '1:673318846822:ios:d7478b555f0c0d3495c8a7',
    messagingSenderId: '673318846822',
    projectId: 'kadu-db',
    storageBucket: 'kadu-db.firebasestorage.app',
    iosBundleId: 'com.example.kadu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsWqGFkxEajPRPxZIfN2zuA_UupbD9pHg',
    appId: '1:673318846822:web:86aeafa217070d7b95c8a7',
    messagingSenderId: '673318846822',
    projectId: 'kadu-db',
    authDomain: 'kadu-db.firebaseapp.com',
    storageBucket: 'kadu-db.firebasestorage.app',
  );
}
